sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ak5055/react_dummy .

script:
  - docker run -e CI=true ak5055/react_dummy npm run test -- --coverage --watchAll=False

