sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t ak5055/react_dummy .

script:
  - docker run -e CI=true ak5055/react_dummy npm run test -- --coverage --watchAll=False

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react_dummy"
  env: "Reactdummy-env"
  bucket_name: "elasticbeanstalk-us-east-1-750615218120"
  bucket_path: "react_dummy"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

